services:
  - type: web
    name: mtbm
    runtime: node
    buildCommand: npm run render-build
    startCommand: cd server && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
